version: '3'
services:
  db:
    image: mariadb:11.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    build: .
    volumes:
      - .:/app:cached
      - bundle-volume:/usr/local/bundle
    ports:
      - 3100:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  bundle-volume:
  db-data:
